import type { Metadata } from "next";
import { Anuphan } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";

const anuphan = Anuphan({
    variable: "--font-anuphan",
    subsets: ["latin"],
    weight: ['400']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={anuphan.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}